### ISSUE TITLE
Code release date

### ISSUE THREAD

**Issue by zdyshine** [IanYeung/MGLD-VSR#1]
Could you tell an approximate date for code realease so that I can start experimenting too? Thanks.

**Comment by IanYeung** [comment]
> Could you tell an approximate date for code realease so that I can start experimenting too? Thanks.

Hi, thank you for your interest in our work. We are cleaning and checking the codes and plan to release it in several weeks.

**Comment by zdyshine** [comment]
Thank you for sharing. May I ask where can I download the file on mgldvsr_512_realbasicvsr_deg.yaml  line 82 ?

**Comment by IanYeung** [comment]
> Thank you for sharing. May I ask where can I download the file on mgldvsr_512_realbasicvsr_deg.yaml line 82 ?

I think you can just comment it out. This is required only if automatic downloading is disabled. Here it is the link: https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/tree/main.

**Comment by zdyshine** [comment]
Thanks, I'll try~~~
