### ISSUE TITLE
How to accelerate inference speed?

### ISSUE THREAD

**Issue by buwangchuxin1992** [IanYeung/MGLD-VSR#15]
Thanks for your excellent work.I wonder how to accelerate inference speed?I have 2 4090 GPU（20G）

**Comment by buwangchuxin1992** [comment]
when I use "python3 scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py" this command,and set "--n_gpus 2",the second 4090 seems not work and An error occurred
![image](https://github.com/user-attachments/assets/e3c12ce5-6344-40b7-b8b6-7fa43d93c0c4)
how to use two 4090 to accelerate the inference speed?thanks

**Comment by IanYeung** [comment]
Currently it need more than 24GB to run the model. This code is somewhat messy and use a naive way to manually split the inference process to multiple cards. Maybe it would be better to use the "split_between_processes" function from the accelerate python library.

**Comment by buwangchuxin1992** [comment]
Thanks for your reply. I successfully run the model in 24G 4090 by change --vqgantile_stride and  default=640 like the following
    parser.add_argument(
        "--vqgantile_stride",
        type=int,
        default=480,
        # default=640,
        # default=750,
        help="the stride for tile operation before VQGAN decoder (in pixel)",
    )
    parser.add_argument(
        "--vqgantile_size",
        type=int,
        #最低512
        default=640,
        # default=720,
        # default=640,
        # default=960,
        help="the size for tile operation before VQGAN decoder (in pixel)",
    )

**Comment by qianx77** [comment]
good ， thanks
