### ISSUE TITLE
Is clip used in LatentDiffusionVSRTextWT?

### ISSUE THREAD

**Issue by zhangyingbit** [IanYeung/MGLD-VSR#20]
Thanks for the interesting work! 
I noticed that in the configuration file, there is a setting related to **cond_stage_config**, which use the model "FrozenOpenCLIPEmbedder".  In the DDPM.py, I only see the text portion here  [https://github.com/IanYeung/MGLD-VSR/blob/main/ldm/models/diffusion/ddpm.py#L3768](https://github.com/IanYeung/MGLD-VSR/blob/main/ldm/models/diffusion/ddpm.py#L3768). Is the default setting [""] for text_cond ?

**Comment by IanYeung** [comment]
Yes, we use null string for text condition.

**Comment by zhangyingbit** [comment]
Thanks for your reply!!! I got it : )
