### ISSUE TITLE
Consultation on data degradation issues

### ISSUE THREAD

**Issue by zdyshine** [IanYeung/MGLD-VSR#3]
basicsr.data.realbasicvsr_dataset has two types of data degradation in the file, RealVSRRecurrentDataset and RealESRGANRecurrentDataset. Have you ever experimented with their differences.

**Comment by IanYeung** [comment]
> basicsr.data.realbasicvsr_dataset has two types of data degradation in the file, RealVSRRecurrentDataset and RealESRGANRecurrentDataset. Have you ever experimented with their differences.

I have not try RealESRGAN degradation yet. It seem to degrade the image/video a bit more stronger than RealBasicVSR one (but in fact it mainly depends on the chosing of degradation parameters).
